services:
  # Backend API Laravel
  backend:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: prueba_backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - ./docker/backend/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - prueba
    environment:
      - APP_ENV=local
      - APP_URL=http://backend

  # Frontend Next.js
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: prueba_frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - prueba
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:80
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development

  db:
    image: mysql:8.0
    container_name: prueba_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: userpassword
      MYSQL_USER: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - prueba

networks:
  prueba:
    driver: bridge

volumes:
  mysql_data:
    driver: local
